#!/usr/bin/env bash

nopass() {
    echo KLUSTER_ENCRYPT not set
    exit 1
}
[[ -z $KLUSTER_ENCRYPT ]] && nopass

for f in $(find . -name '*.enc.yaml'); do
    openssl enc -d -chacha20 -in $f -out ${f%.enc.yaml}.dec.yaml -pbkdf2 -k $KLUSTER_ENCRYPT
done
