#!/usr/bin/env bash

nopass() {
    echo KLUSTER_ENCRYPT not set
    exit 1
}

[[ -z $KLUSTER_ENCRYPT ]] && nopass

for f in $(find . -name '*.dec.yaml'); do
    e=${f%.dec.yaml}.enc.yaml
    openssl enc -chacha20 -in $f -out $e -pbkdf2 -k $KLUSTER_ENCRYPT
    git add $e
done
