{
 "title": "Glass v4",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hardware CPU / Mem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum  by (host) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "CPU {{host}}"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "Mem {{host}}"
    }
   ]
  },
  {
   "title": "Hardware Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (rate(node_network_transmit_bytes_total[1m]))",
     "legendFormat": "Send {{host}}"
    },
    {
     "expr": "- sum by (host) (rate(node_network_receive_bytes_total[1m]))",
     "legendFormat": "Recv {{host}}"
    }
   ]
  },
  {
   "title": "Certificate Ready",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition) (certmanager_certificate_ready_status)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name) (rate(process_cpu_seconds_total{job=\"kubernetes-pods\"}[1m]))",
     "legendFormat": "{{app_kubernetes_io_name}}"
    },
    {
     "expr": "sum by (app_kubernetes_io_name) (rate(process_cpu_seconds_total{job=\"prometheus\"}[1m]))",
     "legendFormat": "prometheus"
    }
   ]
  },
  {
   "title": "Traefik Request 2xx / Other / 1m",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(traefik_service_requests_total{code=~\"2..\"}[1m]))",
     "legendFormat": "{{service}} 2xx"
    },
    {
     "expr": "- sum by (service) (rate(traefik_service_requests_total{code!~\"2..\"}[1m]))",
     "legendFormat": "{{service}} Other"
    }
   ]
  },
  {
   "title": "Prometheus Targets",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets",
     "legendFormat": "{{config}}"
    }
   ]
  },
  {
   "title": "Counters",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (statslogger_beacon_requests)",
     "legendFormat": "beacons"
    },
    { "expr": "sum (statslogger_csp_requests)", "legendFormat": "csp" },
    {
     "expr": "sum by (page) (seankhliao_com_page_requests)",
     "legendFormat": "{{page}}"
    }
   ]
  },
  {
   "title": "Pod RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name) (process_resident_memory_bytes{job=\"kubernetes-pods\"})",
     "legendFormat": "{{app_kubernetes_io_name}}"
    },
    {
     "expr": "sum by (app_kubernetes_io_name) (process_resident_memory_bytes{job=\"prometheus\"})",
     "legendFormat": "prometheus"
    }
   ]
  },
  {
   "title": "usvc Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(usvc_service_latency_s_bucket[5m])) by (le))",
     "legendFormat": "50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(usvc_service_latency_s_bucket[5m])) by (le))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(usvc_service_latency_s_bucket[5m])) by (le))",
     "legendFormat": "99"
    }
   ]
  }
 ]
}