{
 "title": "Glass",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hardware CPU / Mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum  by (host) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "CPU {{host}}"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "Mem {{host}}"
    }
   ]
  },
  {
   "title": "Hardware Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (rate(node_network_transmit_bytes_total{device!~\"wg.*\"}[1m]))",
     "legendFormat": "Send {{host}}"
    },
    {
     "expr": "- sum by (host) (rate(node_network_receive_bytes_total{device!~\"wg.*\"}[1m]))",
     "legendFormat": "Recv {{host}}"
    },
    {
     "expr": "sum by (host) (rate(node_network_transmit_bytes_total{device=~\"wg.*\"}[1m]))",
     "legendFormat": "WG Send {{host}}"
    },
    {
     "expr": "- sum by (host) (rate(node_network_receive_bytes_total{device=~\"wg.*\"}[1m]))",
     "legendFormat": "WG Recv {{host}}"
    }
   ]
  },
  {
   "title": "Vanity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vanity_module_requests", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Calproxy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "calproxy_in_requests", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Traefik Request 2xx / Other / 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(traefik_service_requests_total{code=~\"2..\"}[1m]))",
     "legendFormat": "{{service}} 2xx"
    },
    {
     "expr": "- sum by (service) (rate(traefik_service_requests_total{code!~\"2..\"}[1m]))",
     "legendFormat": "{{service}} Other"
    }
   ]
  },
  {
   "title": "Statslogger",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "statslogger_trigger_count", "legendFormat": "{{trigger}}" }
   ]
  },
  {
   "title": "IPFS Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "targets": [
    { "expr": "ipfs_p2p_peers_total", "legendFormat": "{{transport}}" }
   ]
  },
  {
   "title": "Prometheus Targets",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets",
     "legendFormat": "{{config}}"
    }
   ]
  },
  {
   "title": "Certificate Ready",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "sum by (condition) (certmanager_certificate_ready_status)",
     "legendFormat": "{{condition}}"
    }
   ]
  }
 ]
}